<!DOCTYPE html>
<html>
<head>
	<title>Notification Test</title>
	<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/css/style.css">
	<link rel="stylesheet" type="text/css" href="/js/libs/codemirror/lib/codemirror.css">
	<link rel="stylesheet" type="text/css" href="/js/libs/pnotify/jquery.pnotify.default.css">
	<link rel="stylesheet" type="text/css" href="/js/libs/pnotify/jquery.pnotify.default.icons.css">
	<script src="/js/libs/require/requirejs-2.10.8.min.js"></script>
</head>
<body>
	<?php echo $this->layout()->content ?>
</body>
</html>